# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_initial_focus class ^$ match:title ^$ match:xwayland 1 match:floating 1 match:fullscreen 0 match:pinned 0

# kitty
windowrule = opacity 0.8, match:class kitty

# bluetooth
windowrule = float on, match:class blueman-manager

# retroarch
windowrule = fullscreen on, match:title RetroArch

# tkinter
windowrule = float on, match:class Tk

# wlogout
layerrule = blur on, match:class logout_dialog

# screenkey
windowrule = no_initial_focus on, match:class screenkey
windowrule = float on, match:class screenkey
# slop required?
# windowrule = pin,class:screenkey
# windowrule = size 100% 180,class:screenkey
# windowrule = move onscreen 0 83%,class:screenkey
# windowrule = noborder,class:screenkey
# windowrule = noblur,class:screenkey
# windowrule = nodim,class:screenkey
# windowrule = noshadow,class:screenkey

windowrule = float on, match:title ^(Save As|Save Image|File Upload).*
